[2024-09-06 09:53:31 +0000] [15018] [INFO] Starting gunicorn 23.0.0
[2024-09-06 09:53:31 +0000] [15018] [INFO] Listening at: http://0.0.0.0:5000 (15018)
[2024-09-06 09:53:31 +0000] [15018] [INFO] Using worker: sync
[2024-09-06 09:53:31 +0000] [15019] [INFO] Booting worker with pid: 15019
[2024-09-06 09:53:31 +0000] [15020] [INFO] Booting worker with pid: 15020
[2024-09-06 09:53:31 +0000] [15021] [INFO] Booting worker with pid: 15021
[2024-09-06 09:53:31 +0000] [15022] [INFO] Booting worker with pid: 15022
[2024-09-06 09:54:45 +0000] [15018] [CRITICAL] WORKER TIMEOUT (pid:15019)
[2024-09-06 09:54:45 +0000] [15019] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-09-06 09:54:45 +0000] [15019] [INFO] Worker exiting (pid: 15019)
[2024-09-06 09:54:45 +0000] [15079] [INFO] Booting worker with pid: 15079
[2024-09-06 09:55:43 +0000] [15018] [CRITICAL] WORKER TIMEOUT (pid:15079)
[2024-09-06 09:55:43 +0000] [15079] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-09-06 09:55:43 +0000] [15079] [INFO] Worker exiting (pid: 15079)
[2024-09-06 09:55:43 +0000] [15087] [INFO] Booting worker with pid: 15087
[2024-09-06 09:56:28 +0000] [15018] [CRITICAL] WORKER TIMEOUT (pid:15020)
[2024-09-06 09:56:28 +0000] [15020] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-09-06 09:56:28 +0000] [15020] [INFO] Worker exiting (pid: 15020)
[2024-09-06 09:56:28 +0000] [15088] [INFO] Booting worker with pid: 15088
[2024-09-06 09:58:12 +0000] [15018] [CRITICAL] WORKER TIMEOUT (pid:15087)
[2024-09-06 09:58:12 +0000] [15087] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/my_flask_app/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-09-06 09:58:12 +0000] [15087] [INFO] Worker exiting (pid: 15087)
[2024-09-06 09:58:12 +0000] [15156] [INFO] Booting worker with pid: 15156
